### ISSUE TITLE
Listing 6.5: Delegate for multiple qualified beans not working

### ISSUE THREAD

**Issue by JohnyzHub** [Apress/pro-cdi-2-in-java-ee8#7]
The delegate for multiple beans is not working as described in listing 6.5

When I applied the [@Language](https://github.com/Apress/pro-cdi-2-in-java-ee8/blob/master/chapter6-decorators-and-interceptors/168-qualified-delegate/src/main/java/org/omnifaces/procdi/decorators/greeting/qualified/Language.java) annotation twice on the delegate field, I got the compilation error related to repeatable annotation.
I didn't find any repeatable annotation in this repository. So, I created a repeatable annotation and applied it to Language annotation.

                 --------------------------------------
                 @Retention(RUNTIME)
                 @Target({ FIELD, PARAMETER, METHOD, TYPE})
                 public @interface Languages {
                  	Language[] value();
                 }

                 --------------------------------------
                 @Qualifier
                 @Repeatable(Languages.class)
                 @Retention(RUNTIME)
                 @Target(value = {FIELD, PARAMETER, METHOD, TYPE})
                 public @interface Language {
                    String value();
                 }
                  
                  ------------------------------
                 Inside GreetingDecoratorBean.java
                 @Inject
                 @Delegate
                 @Language("English")
                 @Language("Dutch")
                 private GreetingInterface greetingBean;

When I run the [QualifiedDelegateDemo.java](https://github.com/Apress/pro-cdi-2-in-java-ee8/blob/master/chapter6-decorators-and-interceptors/168-qualified-delegate/src/main/java/org/omnifaces/procdi/decorators/greeting/qualified/QualifiedDelegateDemo.java), decorator was not triggered on any of the qualified beans. I tested this by enabling the decorator in the beans.xml file also with the @Priority annotation on decorator class but no change in the result.

**Comment by janbeernink** [comment]
Many thanks for reporting this! Indeed, the annotation as listed is not a repeatable annotation, which is an error. I will update the errata and will try to add an example in this repository that covers the repeatable annotation on the injected delegate.

**Comment by JohnyzHub** [comment]
Thanks for considering this. 
However, I tried the example with the repeatable annotation, but the decorator was not triggered for any bean. I tried with the decorator class by annotating with @Priority as well as by enabling in beans.xml file. But the decorator didn't got triggered. Do you mean, there much more to add beside repeatable annotation, to make delegate to work for multiple qualified beans?
